### ISSUE TITLE
The build process failed

### ISSUE THREAD

**Issue by Charlie102308** [ginsudev/YTMusicUltimate#231]
I forked the repository and provide the url for a decrypted ipa file for the build and release workflow, during the run of the workflow, an error is encountered during the inject tweak process and I don't know how to solve it
<img width="893" alt="螢幕截圖 2024-03-18 03 14 49" src="https://github.com/ginsudev/YTMusicUltimate/assets/94617775/6fc78c16-bc2e-4d0e-8938-68ece46d6e68">
Please tell me if you understand!! Thank you

**Comment by Hypertext-Assassin-RSS** [comment]
same !!!

**Comment by mustafacakirogludev** [comment]
@Charlie102308 @Hypertext-Assassin-RSS 

Unless you are changed the SDK version before starting the build, its 99% because of the IPA you are providing. Are you guys sure you are giving a proper decrypted IPA? I recommend trying with another decrypted IPA and using dropbox link if you are using something else.

**Comment by Hypertext-Assassin-RSS** [comment]
Thanks ! worked
