### ISSUE TITLE
Hello, do you plan to add the offline mode within downloaded music feature ? Thanks for your work !

### ISSUE THREAD

**Issue by N04-Git** [ginsudev/YTMusicUltimate#50]

**Comment by dayanch96** [comment]
Long tap on artwok image. Only single music downloading

**Comment by Saud-97** [comment]
Ah so it was hidden this way. Is there a plan to make it able to download playlists? 

I have long ones and I would like them to be grouped as playlists instead of all downloaded songs combined in 1 place. YT Premium does allow downloading the playlist but not sure if its doable in modded or not.

But I really am grateful for the efforts and progress on this app.

**Comment by dayanch96** [comment]
> Is there a plan to make it able to download playlists

Not sure. I will take a look

**Comment by Saud-97** [comment]
Sure take your time.

I usually have few playlists saved in my library. So the feature doesn't necessarily have to be usable everywhere just the library would be more than fine.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dayanch96** [comment]
Not the original offline but the ability to download music has been added in 2.0 and newest versions

**Comment by Saud-97** [comment]
Is there plans to allow playlists download? Currently all downloads are saved as a single playlist. So no way currently to store them in separate playlists.

**Comment by dayanch96** [comment]
There no playlists at all
