### ISSUE TITLE
Cant install latest version of v1.3.6 using alt store

### ISSUE THREAD

**Issue by gajein31** [ginsudev/YTMusicUltimate#99]
Cant install latest version of v1.3.6 using alt store. just show home screen generic app icon says cannot install 'youtube music'
Latest IOS

**Comment by IphoneCake** [comment]
Have exactly the same problem. Version 1.2.7 runs perfectly with AltStore. For 1.3.6 you have to use Sideloadly, but with that you don't have the overview when your app expires after seven days. Must set the one reminder then. I also tend to use Altstore instead of Sideloadly. 

Kind regards Dominik

**Comment by dayanch96** [comment]
https://github.com/ginsudev/YTMusicUltimate/issues/93
